# Generated by Django 2.2.5 on 2019-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190909_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos'),
        ),
    ]
