# Generated by Django 2.2.5 on 2019-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bookevent_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookevent',
            name='logo',
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos'),
        ),
    ]
