# Generated by Django 2.2.5 on 2019-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190911_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(null=True, upload_to='restaurant_logos'),
        ),
    ]
