# Generated by Django 2.2.5 on 2019-09-11 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190911_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='choice',
            field=models.CharField(choices=[('cooking', 'cooking'), ('concert', 'concert'), ('Conference', 'Conference'), ('charity', 'charity'), ('art', 'art'), ('play', 'play'), ('others', 'others')], default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookevent',
            name='phone_number',
            field=models.CharField(max_length=120),
        ),
    ]
